---

- name: backgrounds directory
  file:
    path: ~/.backgrounds
    state: directory
  when: background_image is defined

- name: background image
  copy:
    src: "{{background_image}}"
    dest: "{{background_image_path}}"
  when: background_image is defined
