---

- name: remove old binaries
  file:
    path: ~/bin/{{item}}
    state: absent
  loop:
    - etx
    - i3-watchers
    - in2qr
    - on-focus-workspace
    - on-space-shortcut
    - pipe-watcher
    - select-screenlayout
    - timer
