---

- name: disable and stop eralitex vdesk user service
  systemd:
    name: eralitex@:16.service
    state: stopped
    enabled: false
    scope: user
  failed_when: false

- name: remove eralitex user service
  file:
    path: ~/.config/systemd/user/eralitex@.service
    state: absent

- name: remove old eralitex directory
  file:
    path: ~/.eralitex
    state: absent

- name: disable and stop vdesk user service at display 16
  systemd:
    name: vdesk@:16.service
    state: stopped
    enabled: false
    scope: user

- name: disable and stop vdesk user service at display 47
  systemd:
    name: vdesk@:47.service
    state: stopped
    enabled: false
    scope: user

- name: remove vdesk user service
  file:
    path: ~/.config/systemd/user/vdesk@.service
    state: absent
  notify: systemd daemon-reload
