---

- name: desktop app service
  template:
    src: desktop-apps/desktop-app.service.j2
    dest: ~/.config/systemd/user/desktop-app@.service
    mode: 0755
  notify: systemd daemon-reload

- name: autostart terminal
  systemd:
    name: desktop-app@{{default_terminal}}.service
    enabled: "{{ home_autostart_terminal }}"
    scope: user

- name: autostart nm-applet
  systemd:
    name: desktop-app@nm-applet.service
    enabled: "{{ home_autostart_nm_applet }}"
    scope: user

- name: autostart blueman-applet
  systemd:
    name: desktop-app@blueman-applet.service
    enabled: "{{ home_autostart_blueman_applet }}"
    scope: user

- name: autostart pasystray
  systemd:
    name: desktop-app@pasystray.service
    enabled: "{{ home_autostart_pasystray }}"
    scope: user
  when:

- name: autostart unclutter
  systemd:
    name: desktop-app@unclutter.service
    enabled: "{{ home_autostart_unclutter }}"
    scope: user
