---

- name: desktop app service
  template:
    src: desktop-apps/desktop-app.service.j2
    dest: ~/.config/systemd/user/desktop-app@.service
    mode: 0755
  notify: systemd daemon-reload

- name: autostart terminal
  systemd:
    name: desktop-app@{{default_terminal}}.service
    enabled: true
    scope: user

- name: autostart nm-applet
  systemd:
    name: desktop-app@nm-applet.service
    enabled: true
    scope: user
  when: home_profile != "vdesk"

- name: autostart blueman-applet
  systemd:
    name: desktop-app@blueman-applet.service
    enabled: true
    scope: user
  when: home_profile != "vdesk"

- name: autostart unclutter
  systemd:
    name: desktop-app@unclutter.service
    enabled: true
    scope: user
  when: home_profile != "presentation"
