---

- name: lockscreen environment
  template:
    src: lockscreen/lockscreen.env.j2
    dest: ~/.lockscreen.env

- name: screensaver shell script
  template:
    src: lockscreen/screensaver.sh.j2
    dest: ~/.screensaver.sh
    mode: 0755

- name: lockscreen graphical-session service
  template:
    src: lockscreen/lockscreen.service.j2
    dest: ~/.config/systemd/user/lockscreen.service
  notify: systemd daemon-reload

- name: lockscreen graphical-session service enabled
  systemd:
    name: lockscreen.service
    enabled: "{{ lockscreen_enabled }}"
    scope: user
