---

- import_tasks: clean.yaml

- import_tasks: structure.yaml
- import_tasks: ssh.yaml
- import_tasks: vnc.yaml
- import_tasks: tmux.yaml
- import_tasks: pulseaudio.yaml
- import_tasks: git.yaml

- import_tasks: points.yaml

- import_tasks: i3.yaml
  when: home_desktop
- import_tasks: eralitex.yaml
  when: home_desktop
- import_tasks: x11.yaml
  when: home_desktop

- import_tasks: vdesk.yaml
  when: home_desktop

- name: flush handlers
  meta: flush_handlers

- name: enable and start vdesk user service
  systemd:
    name: vdesk@:16.service
    state: started
    enabled: true
    scope: user
  when: home_vdesk_started_and_enabled
