---

- import_tasks: clean.yaml

- import_tasks: structure.yaml
- import_tasks: ssh.yaml
- import_tasks: vnc.yaml
- import_tasks: tmux.yaml
- import_tasks: pulseaudio.yaml
- import_tasks: git.yaml

- import_tasks: kanboard.yaml

- import_tasks: points.yaml

- block:
    - import_tasks: i3.yaml
    - import_tasks: workspaces.yaml
    - import_tasks: background.yaml
    - import_tasks: rofi.yaml
    - import_tasks: x11.yaml
    - import_tasks: vdesk.yaml
  when: home_desktop

- name: flush handlers
  meta: flush_handlers

- name: enable and start vdesk user service
  systemd:
    name: vdesk@:{{home_vdesk_display_number}}.service
    state: started
    enabled: true
    scope: user
  when: home_vdesk_started_and_enabled
