---

- import_tasks: clean.yaml

- import_tasks: structure.yaml
- import_tasks: ssh.yaml
- import_tasks: tmux.yaml
- import_tasks: pulseaudio.yaml
- import_tasks: screensaver.yaml
- import_tasks: git.yaml

- import_tasks: kanboard.yaml

- import_tasks: points.yaml

- block:
    - import_tasks: i3.yaml
    - import_tasks: workspaces.yaml
    - import_tasks: background.yaml
    - import_tasks: rofi.yaml
    - import_tasks: screenlayout.yaml
    - import_tasks: x11.yaml
    - import_tasks: vnc.yaml
    - import_tasks: desktop-apps.yaml
  when: home_desktop

- name: flush handlers
  meta: flush_handlers

- name: enable and start vncserver user service
  systemd:
    name: vncserver@:{{home_vncserver_display_number}}.service
    state: started
    enabled: true
    scope: user
  when: home_vncserver_started_and_enabled
