---

- import_tasks: clean.yaml

- import_tasks: structure.yaml
- import_tasks: path.yaml
- import_tasks: ssh.yaml
- import_tasks: tmux.yaml
- import_tasks: pulseaudio.yaml
- import_tasks: git.yaml
- import_tasks: timer.yaml

- block:
    - import_tasks: i3.yaml
      tags:
        - i3
    - import_tasks: lockscreen.yaml
      tags:
        - lockscreen
    - import_tasks: workspaces.yaml
    - import_tasks: icons.yaml
    - import_tasks: background.yaml
    - import_tasks: xfce4-terminal.yaml
      tags:
        - xfce4-terminal
    - import_tasks: rofi.yaml
    - import_tasks: barrier.yaml
      tags:
        - barrier
    - import_tasks: screenlayout.yaml
    - import_tasks: x11.yaml
      tags:
        - x11
    - import_tasks: vnc.yaml
      tags:
        - vnc
    - import_tasks: desktop-apps.yaml
  when: home_desktop

- name: flush handlers
  meta: flush_handlers

- name: enable and start vncserver user service
  systemd:
    name: vncserver@:{{home_vncserver_display_number}}.service
    state: started
    enabled: true
    scope: user
  when: home_vncserver_started_and_enabled
