---

- name: bin directory
  file:
    path: ~/bin
    state: directory

- name: binaries
  copy:
    src: bin/
    dest: ~/bin
    mode: 0755

- name: systemd user config directory
  file:
    path: ~/.config/systemd/user
    state: directory
