---

- name: ~/bin directory
  file:
    path: ~/bin
    state: directory

- name: systemd user config directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: eralitex directory
  file:
    path: "{{eralitex_directory}}"
    state: directory

- name: profile directories
  file:
    path: "{{eralitex_directory}}/{{item}}"
    state: directory
  with_items: "{{ eralitex_profiles }}"
