---

- name: vdesk user service
  template:
    src: eralitex-vdesk.service.j2
    dest: ~/.config/systemd/user/eralitex@.service
  notify: systemd daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: enable and start eralitex vdesk user service
  systemd:
    name: eralitex@:16.service
    state: started
    enabled: true
    user: true
  when: home_vdesk_started_and_enabled
